CREATE TABLE user_notification_preferences (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR2(64) NOT NULL,
    email_enabled NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT uq_user_pref UNIQUE (user_id, type)
);
