CREATE TABLE email_audit (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(id) ON DELETE SET NULL,
    email VARCHAR2(320) NOT NULL,
    type VARCHAR2(64),
    subject VARCHAR2(255),
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(32),
    error_message VARCHAR2(4000),
    correlation_id VARCHAR2(64),
    metadata CLOB
);
CREATE INDEX idx_email_audit_user ON email_audit(user_id);
