CREATE TABLE email_verification_tokens (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token VARCHAR2(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    consumed NUMBER(1) DEFAULT 0 NOT NULL
);
CREATE INDEX idx_evt_user ON email_verification_tokens(user_id);
