CREATE TABLE password_reset_tokens (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token VARCHAR2(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    consumed NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_prt_user ON password_reset_tokens(user_id);
