-- Create table to remember user-specified ignored source transactions so classification doesn't recreate them
CREATE TABLE tax_classification_ignores (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    source_transaction_id NUMBER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_ignore_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_ignore_source_tx FOREIGN KEY (source_transaction_id) REFERENCES transactions(id),
    CONSTRAINT uq_ignore_user_source UNIQUE (user_id, source_transaction_id)
);

CREATE INDEX idx_ignore_user ON tax_classification_ignores(user_id);
CREATE INDEX idx_ignore_source_tx ON tax_classification_ignores(source_transaction_id);
