-- Tax Deduction Checklist table
CREATE TABLE tax_deduction_checklist (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item VARCHAR2(255) NOT NULL,
    category VARCHAR2(32),
    checked NUMBER(1) DEFAULT 0,
    amount VARCHAR2(32)
);

-- Tax Saving Tips table
CREATE TABLE tax_saving_tips (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    message VARCHAR2(1000) NOT NULL,
    icon VARCHAR2(32)
);