-- Oracle variant of budget_category table
CREATE TABLE budget_category (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(150) NOT NULL,
    monthly_budget NUMBER(19,4) NOT NULL,
    spent NUMBER(19,4) DEFAULT 0 NOT NULL,
    icon VARCHAR2(16),
    color VARCHAR2(16),
    user_id NUMBER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_budget_category_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_budget_category_user_name UNIQUE (user_id, name)
);

CREATE INDEX idx_budget_category_user ON budget_category(user_id);
