CREATE TABLE spending_alerts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    type VARCHAR2(40) NOT NULL,
    severity VARCHAR2(16) NOT NULL,
    title VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000),
    amount NUMBER(19,4),
    merchant VARCHAR2(255),
    category VARCHAR2(150),
    txn_date DATE,
    reason VARCHAR2(400),
    acknowledged NUMBER(1) DEFAULT 0 NOT NULL,
    acknowledged_at TIMESTAMP,
    dismissed NUMBER(1) DEFAULT 0 NOT NULL,
    dismissed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_spending_alerts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT ck_spending_alerts_ack CHECK (acknowledged IN (0,1)),
    CONSTRAINT ck_spending_alerts_dismissed CHECK (dismissed IN (0,1))
);
CREATE INDEX idx_sa_user_created ON spending_alerts(user_id, created_at);
CREATE INDEX idx_sa_user_type ON spending_alerts(user_id, type);
