CREATE TABLE spending_alert_settings (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    large_multiplier NUMBER(10,4) DEFAULT 1.50 NOT NULL,
    large_min_amount NUMBER(19,4) DEFAULT 0 NOT NULL,
    freq_window_hours NUMBER DEFAULT 48 NOT NULL,
    freq_max_txn NUMBER DEFAULT 4 NOT NULL,
    freq_min_amount NUMBER(19,4) DEFAULT 0 NOT NULL,
    cat_spike_multiplier NUMBER(10,4) DEFAULT 2.0 NOT NULL,
    cat_spike_lookback_months NUMBER DEFAULT 3 NOT NULL,
    cat_spike_min_amount NUMBER(19,4) DEFAULT 0 NOT NULL,
    new_merchant_min_amount NUMBER(19,4) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_sa_settings_user UNIQUE(user_id),
    CONSTRAINT fk_sa_settings_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE spending_alert_whitelist (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    merchant VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_sa_whitelist UNIQUE(user_id, merchant),
    CONSTRAINT fk_sa_whitelist_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE spending_alert_muted_category (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    category VARCHAR2(150) NOT NULL,
    mute_until DATE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_sa_muted_cat UNIQUE(user_id, category),
    CONSTRAINT fk_sa_muted_cat_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE spending_alert_audit (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    action VARCHAR2(40) NOT NULL,
    at TIMESTAMP NOT NULL,
    CONSTRAINT fk_sa_audit_alert FOREIGN KEY(alert_id) REFERENCES spending_alerts(id) ON DELETE CASCADE,
    CONSTRAINT fk_sa_audit_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_sa_audit_alert ON spending_alert_audit(alert_id, at);

CREATE TABLE spending_alert_recommendation (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    month VARCHAR2(7) NOT NULL,
    type VARCHAR2(30) NOT NULL,
    priority NUMBER DEFAULT 0 NOT NULL,
    title VARCHAR2(255),
    message VARCHAR2(1000),
    icon VARCHAR2(40),
    category VARCHAR2(150),
    current_monthly_avg NUMBER(19,4),
    suggested_cap NUMBER(19,4),
    rationale VARCHAR2(500),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_sa_reco_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_sa_reco_user_month ON spending_alert_recommendation(user_id, month);
