-- V25 (Oracle): Create goal table
-- Oracle-specific variant (separate directory picked up by Flyway for Oracle datasource).

DECLARE
    v_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'GOAL';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[CREATE TABLE goal (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            title VARCHAR2(120) NOT NULL,
            description VARCHAR2(500),
            target_amount NUMBER(19,4) NOT NULL,
            current_amount NUMBER(19,4) DEFAULT 0 NOT NULL,
            target_date DATE,
            category VARCHAR2(50),
            icon VARCHAR2(64),
            color VARCHAR2(32),
            monthly_contribution NUMBER(19,4) DEFAULT 0,
            user_id NUMBER NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT fk_goal_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )]';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_goal_user ON goal(user_id)';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_goal_user_target_date ON goal(user_id, target_date)';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_goal_set_updated
BEFORE UPDATE ON goal
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/
