-- Renamed from V027__notification_prefs.sql because version 27 already applied.
-- Creates user notification preference table (idempotent guards added for Oracle)
DECLARE
  v_table_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO v_table_exists FROM user_tables WHERE table_name = 'USER_NOTIFICATION_PREFERENCES';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE user_notification_preferences (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id NUMBER NOT NULL,
        type VARCHAR2(64) NOT NULL,
        email_enabled NUMBER(1) DEFAULT 1 NOT NULL,
        CONSTRAINT uq_user_pref UNIQUE (user_id, type),
        CONSTRAINT fk_user_pref_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    )';
  END IF;
END;
/
