-- Oracle variant: add billing_period column and seed yearly plan rows.
DECLARE
  v_col_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO v_col_exists FROM user_tab_cols WHERE table_name = 'PLANS' AND column_name = 'BILLING_PERIOD';
  IF v_col_exists = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PLANS ADD (BILLING_PERIOD VARCHAR2(16) DEFAULT ''MONTHLY'')';
  END IF;
  EXECUTE IMMEDIATE 'UPDATE PLANS SET BILLING_PERIOD = ''MONTHLY'' WHERE BILLING_PERIOD IS NULL';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Drop old unique constraint if exists, then add new one including billing_period
DECLARE
  v_constraint_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO v_constraint_exists FROM user_constraints WHERE table_name='PLANS' AND constraint_name='UQ_PLAN_TYPE_REGION';
  IF v_constraint_exists = 1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PLANS DROP CONSTRAINT UQ_PLAN_TYPE_REGION';
  END IF;
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PLANS ADD CONSTRAINT UQ_PLAN_TYPE_REGION_PERIOD UNIQUE (PLAN_TYPE, REGION, BILLING_PERIOD)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Helper procedure for inserting yearly variants
DECLARE
  PROCEDURE ins_yearly(p_plan_type VARCHAR2, p_region VARCHAR2, p_multiplier NUMBER) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM PLANS WHERE PLAN_TYPE=p_plan_type AND REGION=p_region AND BILLING_PERIOD='YEARLY';
    IF v_count = 0 THEN
      INSERT INTO PLANS (PLAN_TYPE, REGION, CURRENCY, AMOUNT, STATEMENTS_PER_MONTH, PAGES_PER_STATEMENT, FEATURES, COMBINED_BANK, BILLING_PERIOD)
      SELECT PLAN_TYPE, REGION, CURRENCY, AMOUNT * p_multiplier, STATEMENTS_PER_MONTH, PAGES_PER_STATEMENT, FEATURES, COMBINED_BANK, 'YEARLY'
      FROM PLANS WHERE PLAN_TYPE=p_plan_type AND REGION=p_region AND BILLING_PERIOD='MONTHLY' FETCH FIRST 1 ROWS ONLY;
    END IF;
  END;
BEGIN
  ins_yearly('PRO','IN',10);
  ins_yearly('PREMIUM','IN',10);
  ins_yearly('PRO','US',10);
  ins_yearly('PREMIUM','US',10);
  ins_yearly('PRO','EU',10);
  ins_yearly('PREMIUM','EU',10);
END;
/