-- V8: Link tax_transactions to original transactions & add rule engine scaffolding
-- Adds source_transaction_id, rule_id, classification_status columns
-- Creates tax_deduction_rules table

-- Add columns idempotently via exception handling (no shared variables needed)
DECLARE
	e_col_exists EXCEPTION; PRAGMA EXCEPTION_INIT(e_col_exists, -1430); -- ORA-01430 column exists
BEGIN
	BEGIN EXECUTE IMMEDIATE 'ALTER TABLE tax_transactions ADD (source_transaction_id NUMBER)'; EXCEPTION WHEN e_col_exists THEN NULL; END;
	BEGIN EXECUTE IMMEDIATE 'ALTER TABLE tax_transactions ADD (rule_id NUMBER)'; EXCEPTION WHEN e_col_exists THEN NULL; END;
	BEGIN 
		EXECUTE IMMEDIATE 'ALTER TABLE tax_transactions ADD (classification_status VARCHAR2(16) DEFAULT ''CONFIRMED'')'; 
	EXCEPTION WHEN e_col_exists THEN NULL; END;
	-- Backfill classification_status regardless (safe)
	BEGIN EXECUTE IMMEDIATE 'UPDATE tax_transactions SET classification_status = ''CONFIRMED'' WHERE classification_status IS NULL'; EXCEPTION WHEN OTHERS THEN NULL; END;
END;
/

-- Constraints (idempotent via data dictionary checks)
DECLARE
	v_cnt NUMBER;
BEGIN
	SELECT COUNT(*) INTO v_cnt FROM user_constraints WHERE table_name='TAX_TRANSACTIONS' AND constraint_name='FK_TAX_TX_SOURCE_TX';
	IF v_cnt = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE tax_transactions ADD CONSTRAINT fk_tax_tx_source_tx FOREIGN KEY (source_transaction_id) REFERENCES transactions(id) ON DELETE SET NULL';
	END IF;
END;
/
DECLARE
	v_cnt NUMBER;
BEGIN
	SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE table_name='TAX_TRANSACTIONS' AND index_name='UQ_TAX_TX_SOURCE';
	IF v_cnt = 0 THEN
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uq_tax_tx_source ON tax_transactions(source_transaction_id)';
	END IF;
END;
/

DECLARE
	e_table_exists EXCEPTION; PRAGMA EXCEPTION_INIT(e_table_exists, -955); -- ORA-00955 name is already used
BEGIN
	BEGIN
		EXECUTE IMMEDIATE 'CREATE TABLE tax_deduction_rules (
			id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id NUMBER NULL REFERENCES users(id) ON DELETE CASCADE,
			match_type VARCHAR2(32) NOT NULL,
			match_value VARCHAR2(500) NOT NULL,
			tax_category_code VARCHAR2(64) NOT NULL REFERENCES tax_categories(code),
			priority NUMBER DEFAULT 0 NOT NULL,
			auto_mark_deductible NUMBER(1) DEFAULT 1 NOT NULL,
			active NUMBER(1) DEFAULT 1 NOT NULL,
			created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
		)';
	EXCEPTION WHEN e_table_exists THEN NULL; END;
	BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_tax_rules_user_active ON tax_deduction_rules(user_id, active, priority)'; EXCEPTION WHEN e_table_exists THEN NULL; END;
END;
/

